<?php

namespace Proyecto\MainBundle\Repository;

/**
 * EnfermedadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfermedadRepository extends \Doctrine\ORM\EntityRepository
{
}
