<?php

namespace Proyecto\MainBundle\Repository;

/**
 * IndicacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndicacionesRepository extends \Doctrine\ORM\EntityRepository
{
}
