<?php

namespace Proyecto\MainBundle\Repository;

/**
 * MedicamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicamentoRepository extends \Doctrine\ORM\EntityRepository
{
}
