<?php

namespace Proyecto\MainBundle\Repository;

/**
 * PadecerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PadecerRepository extends \Doctrine\ORM\EntityRepository
{
}
